services:
  postgres:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=avayar_user
      - POSTGRES_PASSWORD=cvV895xP8AnTbfbekCvgwSWvyAzzfSff
      - POSTGRES_DB=avayar_db
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    restart: always
  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
